# Site settings
name: Linshu Yang
title: Linshu Yang
description: A first-year Computer Science master's student
url: https://mpi.run/
baseurl: ''
email: linshuy2@illinois.edu
logo: /img/emojis/tree.png
resume: /static/docs/resume.pdf
social:
  - title: resume
    url: /static/docs/resume.pdf
  - title: email
    url: mailto:linshuy2@illinois.edu
  - title: github
    url: https://github.com/profetia
  - title: linkedin
    url: https://www.linkedin.com/in/ly4ng

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - 'shell.nix'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
